version: "3.9"

services:
  keycloak:
    container_name: "minigoodreads_keycloak"
    hostname: "minigoodreads_keycloak"
    image: "quay.io/keycloak/keycloak:20.0"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: "mysql"
      KC_DB_URL_HOST: "minigoodreads_mysql"
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
    command: "start-dev"
  mysql:
    container_name: "minigoodreads_mysql"
    hostname: "minigoodreads_mysql"
    image: "minigoodreads/mysql-server:8.0.32"
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    volumes:
      - "mysql_data:/var/lib/mysql"

networks:
  default:
    name: "minigoodreads_network"

volumes:
  mysql_data: