version: "3.9"

services:
  mysql:
    container_name: "minigoodreads_mysql"
    hostname: "minigoodreads_mysql"
    image: "minigoodreads/mysql-server:8.0.32"
    build:
      context: docker/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "minigoodreads"
      MYSQL_ROOT_PASSWORD: "root"
  minigoodreads:
    container_name: "minigoodreads_be"
    hostname: "minigoodreads_be"
    image: "minigoodreads/be:1.0.0"
    build:
      context: .
      dockerfile: docker/minigoodreads/Dockerfile
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: "minigoodreads_mysql"
      DB_NAME: "minigoodreads"
      DB_USERNAME: "minigoodreads"
      DB_PASS: "minigoodreads"

networks:
  default:
    name: "minigoodreads_network"

volumes:
  mysql_data: