package gr.hua.dit.minigoodreads.entity;

public enum EventNames {
	EVENT_BOOK_SEARCH,
	EVENT_LIST_CREATE,
	EVENT_LIST_DELETE,
	EVENT_LIST_RENAME,
	EVENT_BOOK_IN_LIST_ADD,
	EVENT_BOOK_IN_LIST_REMOVE,
	EVENT_READING_PROGRESS_UPDATE
}
